### ISSUE TITLE
Replace @post_dump with NameSpaced schema/opts

### ISSUE THREAD

**Issue by sbreidba** [Pythonistas/Gatekeeper#10]
Reference here: http://marshmallow.readthedocs.org/en/latest/extending.html, very bottom.

**Comment by crphillip** [comment]
Added two new feature branches (update_image and update_owner).  Clean up is complete.  I'll need a little direction on creating the pull request or finishing feature(s).

**Comment by crphillip** [comment]
Completed August 27. Marking closed.
